name: Docker Push

on:
  repository_dispatch:
    types: [docker-scan-complete]

env:
  REGISTRY: docker.io
  IMAGE_NAME: antonbiz/file-toolkit

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push multi-platform image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ github.event.client_payload.image-tags }}
        cache-from: type=gha

    - name: Image pushed successfully
      run: |
        echo "🎉 Docker image pushed successfully!"
        echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        echo "Digest: ${{ github.event.client_payload.image-digest }}"
        echo "Tags: ${{ github.event.client_payload.image-tags }}"
