name: gopls-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run gopls lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install gopls
        run: |
          go install golang.org/x/tools/gopls@latest

      - name: Run gopls lint
        run: |
          find . -name '*.go' -print0 | xargs -0 gopls check
